# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNegativelogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_negativelogin(self):
    self.driver.get("https://auth.cloudike.com/?ticket_id=6a40429394414c96a408dbb83ab17400")
    self.driver.set_window_size(1440, 900)
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").send_keys("nkiyashko")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched").send_keys("500875875g")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").send_keys("nkiyashko@")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").send_keys("nkiyashko@gmail")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").send_keys("nkiyashkogmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").send_keys("nkiyashko@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").send_keys("500875875")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-primary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(1)").send_keys("500875875g")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon use").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(2)").send_keys("nkiyashko@asdco.ru")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
